# SPDX-FileCopyrightText: 2026 Ashlesha T
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import cognirepo_pb2 as cognirepo__pb2
except ImportError:
    import cognirepo_pb2 as cognirepo__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cognirepo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub(object):
    """─── QueryService ────────────────────────────────────────────────────────────
    Used by any model adapter to delegate sub-queries to other models.
    Pattern: DEEP query → Claude reasons → calls SubQuery(Gemini Flash) → resumes.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubQuery = channel.unary_unary(
                '/cognirepo.QueryService/SubQuery',
                request_serializer=cognirepo__pb2.QueryRequest.SerializeToString,
                response_deserializer=cognirepo__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.SubQueryStream = channel.unary_stream(
                '/cognirepo.QueryService/SubQueryStream',
                request_serializer=cognirepo__pb2.QueryRequest.SerializeToString,
                response_deserializer=cognirepo__pb2.QueryResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """─── QueryService ────────────────────────────────────────────────────────────
    Used by any model adapter to delegate sub-queries to other models.
    Pattern: DEEP query → Claude reasons → calls SubQuery(Gemini Flash) → resumes.

    """

    def SubQuery(self, request, context):
        """Fire a sub-query at a specific model tier; returns result + confidence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubQueryStream(self, request, context):
        """Streaming version — model sends result tokens incrementally.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SubQuery,
                    request_deserializer=cognirepo__pb2.QueryRequest.FromString,
                    response_serializer=cognirepo__pb2.QueryResponse.SerializeToString,
            ),
            'SubQueryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SubQueryStream,
                    request_deserializer=cognirepo__pb2.QueryRequest.FromString,
                    response_serializer=cognirepo__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognirepo.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognirepo.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """─── QueryService ────────────────────────────────────────────────────────────
    Used by any model adapter to delegate sub-queries to other models.
    Pattern: DEEP query → Claude reasons → calls SubQuery(Gemini Flash) → resumes.

    """

    @staticmethod
    def SubQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognirepo.QueryService/SubQuery',
            cognirepo__pb2.QueryRequest.SerializeToString,
            cognirepo__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubQueryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cognirepo.QueryService/SubQueryStream',
            cognirepo__pb2.QueryRequest.SerializeToString,
            cognirepo__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ContextServiceStub(object):
    """─── ContextService ──────────────────────────────────────────────────────────
    Shared session context — any model can push/pull partial reasoning state.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushContext = channel.unary_unary(
                '/cognirepo.ContextService/PushContext',
                request_serializer=cognirepo__pb2.ContextSyncRequest.SerializeToString,
                response_deserializer=cognirepo__pb2.ContextSyncResponse.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/cognirepo.ContextService/GetContext',
                request_serializer=cognirepo__pb2.ContextGetRequest.SerializeToString,
                response_deserializer=cognirepo__pb2.ContextGetResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/cognirepo.ContextService/ListSessions',
                request_serializer=cognirepo__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=cognirepo__pb2.ListSessionsResponse.FromString,
                _registered_method=True)


class ContextServiceServicer(object):
    """─── ContextService ──────────────────────────────────────────────────────────
    Shared session context — any model can push/pull partial reasoning state.

    """

    def PushContext(self, request, context):
        """Push partial context (intermediate reasoning, sub-results) to shared store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Pull current context for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List all active session IDs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushContext': grpc.unary_unary_rpc_method_handler(
                    servicer.PushContext,
                    request_deserializer=cognirepo__pb2.ContextSyncRequest.FromString,
                    response_serializer=cognirepo__pb2.ContextSyncResponse.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=cognirepo__pb2.ContextGetRequest.FromString,
                    response_serializer=cognirepo__pb2.ContextGetResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=cognirepo__pb2.ListSessionsRequest.FromString,
                    response_serializer=cognirepo__pb2.ListSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognirepo.ContextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognirepo.ContextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextService(object):
    """─── ContextService ──────────────────────────────────────────────────────────
    Shared session context — any model can push/pull partial reasoning state.

    """

    @staticmethod
    def PushContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognirepo.ContextService/PushContext',
            cognirepo__pb2.ContextSyncRequest.SerializeToString,
            cognirepo__pb2.ContextSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognirepo.ContextService/GetContext',
            cognirepo__pb2.ContextGetRequest.SerializeToString,
            cognirepo__pb2.ContextGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognirepo.ContextService/ListSessions',
            cognirepo__pb2.ListSessionsRequest.SerializeToString,
            cognirepo__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
